apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-aks-iot-platform-mosquitto-config
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true

    persistence true
    persistence_location /mosquitto/data/

    log_dest stdout
    log_type error
    log_type warning
    log_type notice
    log_type information
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-aks-iot-platform-mosquitto-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-aks-iot-platform-mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/part-of: azure-aks-iot-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/part-of: azure-aks-iot-platform
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
        app.kubernetes.io/part-of: azure-aks-iot-platform
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.1.2-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
              readOnly: true
            - name: mosquitto-data
              mountPath: /mosquitto/data
      volumes:
        - name: mosquitto-config
          configMap:
            name: azure-aks-iot-platform-mosquitto-config
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: azure-aks-iot-platform-mosquitto-data
---
apiVersion: v1
kind: Service
metadata:
  name: azure-aks-iot-platform-mosquitto
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/part-of: azure-aks-iot-platform
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
