FROM ros:jazzy-ros-base

SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libpaho-mqtt-dev \
        libpaho-mqttpp-dev \
        libcpp-httplib-dev \
        nlohmann-json3-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

COPY interfaces/ros2-command/ \
  /workspace/src/vagotec_iot_interfaces/

COPY services/backend/src/ \
  /workspace/src/vagotec_backend_service/

RUN source /opt/ros/jazzy/setup.bash && \
    colcon build \
      --merge-install \
      --packages-up-to vagotec_backend_service

COPY services/backend/container/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
