apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: azure-aks-iot

resources:
  - namespace.yaml
  - ../../base
  - gateway

images:
  - name: azure-aks-iot-platform-backend
    newName: ghcr.io/vagotec/azure-aks-iot-platform-backend
    newTag: latest

  - name: azure-aks-iot-platform-ros2-simulator
    newName: ghcr.io/vagotec/azure-aks-iot-platform-ros2-simulator
    newTag: latest

  - name: azure-aks-iot-platform-frontend
    newName: ghcr.io/vagotec/azure-aks-iot-platform-frontend
    newTag: latest
